//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Esoft_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class RealEstateSet
    {
        public int id { get; set; }
        public string Address_City { get; set; }
        public string Address_Street { get; set; }
        public string Adress_House { get; set; }
        public string Adress_Number { get; set; }
        public Nullable<double> Coordinate_latitube { get; set; }
        public Nullable<double> Coordinate_longitube { get; set; }
        public int Type { get; set; }
        public Nullable<double> TotalArea { get; set; }
        public Nullable<int> TotalFloosr { get; set; }
        public Nullable<int> Rooms { get; set; }
        public Nullable<int> Floor { get; set; }
    }
}
